services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_gerencia_encomenda
    restart: always
    environment:
      - 'POSTGRES_DB=gerencia_encomenda'
      - 'POSTGRES_PASSWORD=senha123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5440:5432'
