spring.application.name=gerencia-encomenda

server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5440/gerencia_encomenda
spring.datasource.username=admin
spring.datasource.password=senha123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

