spring.application.name=gerencia-encomenda

server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5440/gerencia_encomenda
spring.datasource.username=admin
spring.datasource.password=senha123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# PUBLISHER
spring.cloud.stream.bindings.notificacaoOutput-out-0.destination=notificacao-topic
spring.cloud.stream.bindings.notificacaoOutput-out-0.content-type=application/json

# LISTENER
spring.cloud.stream.bindings.notificacaoInput-in-0.destination=notificacao-topic
spring.cloud.stream.bindings.notificacaoInput-in-0.content-type=application/json
spring.cloud.stream.bindings.notificacaoInput-in-0.group=notificacao-group

# KAFKA CONFIG
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.auto-create-topics=true

# Resend
resend.api-key=re_LpRNY2XJ_9xGtkKj8T3LfFs9XCZaDbRBB
resend.from-email=onboarding@resend.dev